name: Auto Deploy Backend to Vercel

on:
  push:
    branches:
      - main  # Change this if your deployment branch is different

jobs:
  deploy:
    name: Trigger Vercel Deploy Hook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Trigger Vercel Deploy Hook
        run: |
          curl --fail --silent --show-error \
              -X POST "https://api.vercel.com/v1/integrations/deploy/prj_QqM7MeqPPvoH53HBt10ToxB8z23Z/zR4rX0uiY8"